### ISSUE TITLE
Uncaught TypeError: Cannot read property 'CreateClipsFromMorphTargetSequences' of undefined

### ISSUE THREAD

**Issue by jupiterkenji** [foxdog-studios/meteor-threejs#1]
I try to load MD2 and it throw the aforementioned error.

It seems that the version of three.min.js is missing: three.js/src/animation/AnimationClip.js

I tried to update three.min.js using latest threeJS but it throw further error:
DeviceOrientationControls.js:8Uncaught TypeError: Cannot set property 'DeviceOrientationControls' of undefined(anonymous function) @ DeviceOrientationControls.js:8(anonymous function) @ fds_threejs.js?dff7f79d2bc1103814f79e6902c58fb05516998e:2059(anonymous function) @ fds_threejs.js?dff7f79d2bc1103814f79e6902c58fb05516998e:20443
kwatjh-threejs.js?88dcc00a883a84b1a4139ea38ae042e9ac506a4f:15Uncaught TypeError: Cannot read property 'THREE' of undefined(anonymous function) @ kwatjh-threejs.js?88dcc00a883a84b1a4139ea38ae042e9ac506a4f:15(anonymous function) @ kwatjh-threejs.js?88dcc00a883a84b1a4139ea38ae042e9ac506a4f:496

Do you know when you will update the three.min.js? or perhaps I can help you do it?

**Comment by dj-foxxy** [comment]
Thanks for flagging this up. I've updated the package. Please run `meteor update fds:threejs` in your Meteor application or update your `package.js`.
