### ISSUE TITLE
`TextureLoader` undefined?

### ISSUE THREAD

**Issue by chiroptical** [foxdog-studios/meteor-threejs#2]
Hey @dj-foxxy, I am getting the following error and I was hoping you could help me out. I am just running `THREE.TextureLoader()` in the Chrome console and it returns `undefined`, but when I use the "old" syntax `THREE.ImageUtils.load(...)` (something like this) I get "Function is deprecated, use TextureLoader instead".

Any thoughts?

**Comment by chiroptical** [comment]
I think I figured this out. I need to expose the loader inside the package. I am going to fork this and create a package which fits my needs.

**Comment by dj-foxxy** [comment]
Hi @barrymoo. Thanks for creating an issue. I'm trying to find the problem. `TextureLoader` is defined on the exported `THREE` object. Can you post the code that is causing the error?

**Comment by chiroptical** [comment]
Honestly @dj-foxxy, I think I just need more experience with three.js. I wouldn't worry about me ha. Thanks!

**Comment by vincentmader** [comment]
@chiroptical Do you still know how you fixed this? I'm getting the same error.

**Comment by chiroptical** [comment]
I don't even remember working on this unfortunately, I would open a new issue
